RENAME_UNIT_TYPE = {
    "Distillate Hydrotreater":                  "DHTU",
    "Reformer Feed Hydrotreater":               "REMOVE",
    "Vacuum Distillation":                      "VDU",
    "Sulfuric Alkylation":                      "Alky",
    "Atmospheric Distillation":                 "CDU",
    "Aromatics":                                "Aroms",
    "BTX (Benzene-Toluene-Xylene)":             "Aroms",
    "Amine Treatment":                          "REMOVE",
    "Olefin/Aromatics Hydrotreater":            "REMOVE",
    "Asphalt":                                  "REMOVE",
    "Residual Hydrotreater":                    "REMOVE",
    "Condensate Splitter":                      "CDU",
    "Isomerization":                            "Isom",
    "Benzene":                                  "Aroms",
    "CCR (Continuous Catalytic Reformer)":      "Reformer",
    "FCCU (Fluid Catalytic Cracker)":           "FCCU",
    "FCCU Feed Hydrotreater":                   "REMOVE",
    "Mid Distillate Hydrotreater":              "DHTU",
    "FCCU Gasoline Hydrotreater":               "REMOVE",
    "Refinery Gas/Lights Ends":                 "REMOVE",
    "Sulfur Recovery (SRU)":                    "REMOVE",
    "Semiregen/Cyclic Reformer":                "Reformer",
    "Petroleum Coke Calciner":                  "REMOVE",
    "HGO (Heavy Gas Oils) Hydrotreater":        "REMOVE",
    "Light Naphtha Hydrotreater":               "REMOVE",
    "Solvent Extraction":                       "REMOVE",
    "Delayed Coker":                            "Coker / Visbreaker",
    "Distillate Hydrocracker":                  "Hydrocracker",
    "Diesel Hydrotreater":                      "DHTU",
    "Diluent Recovery Unit (DRU)":              "REMOVE",
    "Naphtha Splitter":                         "REMOVE",
    "Lube Oil Dewaxing":                        "REMOVE",
    "VRU (Vapor Recovery Unit)":                "REMOVE",
    "Fluidized-Bed Coker":                      "Coker / Visbreaker",
    "Lube Oil Finishing":                       "REMOVE",
    "Sour Water Stripper":                      "REMOVE",
    "Hydrogen (H2) Production":                 "REMOVE",
    "Hydrodealkylation":                        "Alky",
    "Lube Oil Hydrotreater":                    "REMOVE",
    "Hydrofluoric Alkylation":                  "Alky",
    "Hydrogen (H2) Recovery":                   "REMOVE",
    "SR (Straight-Run) Hydrotreater":           "DHTU",
    "Residual Hydrocracker":                    "Hydrocracker",
    "Ionic Salt (Liquid) Alkylation":           "Alky",
    "Mercaptan-Extraction":                     "REMOVE",
    "Lube Oil Hydrocracker":                    "REMOVE",
    "MTBE (Methyl tert Butyl Ether)":           "REMOVE",
    "Tail Gas Treater":                         "REMOVE",
    "Propylene Splitter":                       "REMOVE",
    "Paraxylene":                               "Aroms",
    "RFCCU (Residue Fluid Catalytic Cracker)":  "FCCU",
    "Reformate Splitter":                       "REMOVE",
    "TAME (Tertiary Amyl Methyl Ether)":        "REMOVE",
    "Visbreaker":                               "Coker / Visbreaker",
    "Crude Stabilization":                      "REMOVE",
    "Linear Alkyl Benzene (LAB)":               "REMOVE",
    "Toluene":                                  "Aroms",
    "Vacuum (No Atmospheric)":                  "VDU",
    "Xylene":                                   "Aroms",
    "ETBE (Ethyl tert Butyl Ether)":            "REMOVE",
}

PADD_RENAME = {
    "I":   "PADD 1",
    "II":  "PADD 2",
    "III": "PADD 3",
    "IV":  "PADD 4",
    "V":   "PADD 5",
}
